### ISSUE TITLE
Use environment to configure Drupal development

### ISSUE THREAD

**Issue by yannlugrin** [antistatique/docker-php-dev#7]
Create our own `settings.local.php` file stored in the image, that use environment variable to set value for cache & co. Then include this file in generated `settings.php`.

**Comment by gido** [comment]
Some examples:
 -  https://github.com/antistatique/faa/blob/dev/web/sites/default/settings.php#L825-L836
 - (for D7 setup): https://github.com/antistatique/a-capella/compare/67bd9ddb48151b88cc2d94f9c0d46e36a739ecef...95f8690a13f6e01b442881cccbc6e9f3d1249235

**Comment by WengerK** [comment]
it's done nop @gido ?

**Comment by gido** [comment]
We can close this one in favor of #29. It's not completely done because the script still edit on the fly the settings.php and I want to remove this part.

**Comment by WengerK** [comment]
thanks for the update
